import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const server = readFileSync(join(root, "server.ts"), "utf8");
const publication = readFileSync(join(root, "components/detail/build-publication.tsx"), "utf8");
const diff = readFileSync(join(root, "components/detail/build-diff.tsx"), "utf8");
const app = readFileSync(join(root, "app.tsx"), "utf8") + publication;

for (const method of ["publicationStatus", "publicationCommitDiff", "publicationCommit", "publicationSquashMerge", "publicationPushTerminal", "publicationPushTerminals", "publicationPullPush", "publicationPullRequestAction"]) {
  assert.match(server, new RegExp(`async ${method}\\(`), `${method} RPC exists`);
}
assert.match(server, /bb\.sdk\.environments\.status/, "publication status is owned by BB");
assert.match(server, /bb\.sdk\.environments\.commit/, "commit is routed to BB's environment host");
assert.match(server, /buildSquashScript\(\{ base, branch/, "local squash merge runs git merge --squash in the card's own shell (BB exposes no local squash action)");
assert.match(server, /parseSquashOutput\(tail\)/, "the squash verdict is parsed from terminal output, never assumed");
assert.match(server, /verdict\.finished/, "the squash shell is only closed after the branch restore runs");
assert.match(server, /bb\.sdk\.environments\.markPullRequestReady/, "PR ready transition is routed to BB");
assert.match(server, /bb\.sdk\.environments\.markPullRequestDraft/, "PR draft transition is routed to BB");
assert.match(server, /bb\.sdk\.environments\.mergePullRequest/, "PR merge is routed to BB");
assert.match(server, /publicationSnapshot\(card\)/, "each mutating action runs a fresh preflight");
assert.match(server, /canMarkPullRequestReady\(status, pullRequest\)/, "ready transition shares the workspace safety policy");
assert.match(server, /canMarkPullRequestDraft\(status, pullRequest\)/, "draft transition shares the workspace safety policy");
assert.match(server, /publication_events/, "publication writes are separately auditable");
assert.match(server, /commit_sha = \?/, "commit review is limited to card-recorded publication history");
assert.match(server, /bb\.sdk\.environments\.diffFiles/, "commit review uses BB's native environment diff API");
assert.match(server, /bb\.sdk\.environments\.diffPatch/, "missing file patches are fetched from BB instead of given up on");
assert.match(server, /bb\.sdk\.terminals\.create/, "push opens a visible BB terminal instead of pushing silently");
assert.match(server, /start: \{ mode: "shell" \}/, "the push shell stays open for review instead of exiting like a one-shot command");
assert.match(server, /terminals\.input/, "git push is sent to the card's own shell, never run on an assumed host");
assert.match(server, /STELOW_PUSH_EXIT/, "the shell reports the push exit so the panel can name the outcome");
assert.match(server, /scope: \{ kind: "environment", environmentId/, "the push terminal runs in the card's own environment, never an assumed host");
assert.match(server, /push_terminal/, "terminal pushes enter publication history");
assert.match(server, /Ran pull --rebase \+ push in shell/, "sync runs enter history under the same auditable action");
assert.match(server, /publicationPullPush/, "rejected pushes have a one-click pull-rebase-plus-push remediation");
assert.match(server, /pull --rebase/, "the decided workflow is rebase (linear history, no merge commits for lay users)");
assert.match(server, /STELOW_SYNC_EXIT/, "the pull step reports its own exit separately from the push");
assert.match(server, /STELOW_SYNC_ABORTED/, "a conflicted pull aborts itself instead of stranding the checkout mid-rebase");
assert.match(server, /REBASE_HEAD/, "conflict detection reads rebase state, not output text");
assert.match(app, /Sync & push/, "a rejected push offers remediation where the failure is shown");
assert.match(app, /Sync &amp; push again/, "failed shells carry their own retry that syncs first");
assert.match(app, /STELOW_SYNC_ABORTED:1/, "an aborted sync names the manual exit instead of a dead end");
assert.doesNotMatch(app, /pull first in BB’s sidebar terminal/, "push remediation never sends the user to hunt the sidebar");
assert.match(app, /execCommand\("copy"\)/, "copy falls back to the legacy path when the Clipboard API is unavailable");
assert.match(app, /select and copy by hand:/, "an uncopyable value still reaches the user inside the error");
assert.match(server, /could not be sent/, "a swallowed terminal-input failure never reports success with an empty shell");
assert.match(server, /publicationPushTerminals/, "push shells stay consultable after creation, never toast-only");
assert.match(server, /terminals\.list/, "consulting push shells lists the card environment's terminals");
assert.match(server, /terminals\.output/, "consulting push shells reads live terminal output");
assert.match(server, /outputTail/, "terminal output survives as a readable tail in the panel");
assert.match(server, /rewrites one line via/, "progress spam collapses the way a real terminal renders it, keeping errors");
assert.match(app, /Push shells/, "the panel tracks push shells with live output instead of sending the user to hunt the sidebar");
assert.match(app, /Copy terminal ID/, "each push shell names its real BB terminal for sidebar lookup");
assert.match(app, /Snapshot — refresh with Check result/, "the embedded output admits it is a snapshot, not an interactive terminal");
assert.match(app, /○ Ended — output unavailable/, "an exited shell with no scrollback never reports Running");
assert.match(app, /No push shell opened yet\./, "empty push state stays quiet when the action sits right above it");
assert.match(server, /already running in shell/, "a second push while one is in flight is refused instead of duplicating shells");
assert.match(server, /pushShellSessions/, "one push shell per card: predecessors are found before creating");
assert.match(server, /mode: "force"/, "retired finished/waiting shells are closed so runs never accumulate");
assert.match(app, /Check result/, "push results are re-checkable after execution");
assert.match(app, /Push now…/, "pushing is an explicit confirmed action that runs in the card's checkout");
assert.match(app, /Push branch/, "the push confirmation names the action it takes");
assert.match(app, /✓ Pushed/, "a finished push reads as pushed, not as raw terminal text");
assert.match(app, /Waiting — git push typed but NOT sent/, "legacy typed-only shells name what is missing instead of looking executed");
assert.match(server, /stelow commit diff: diffPatch (unavailable|failed)/, "patch fetch failures are logged for diagnosis instead of swallowed");
assert.match(server, /initialPatches is empty even/, "commit targets fetch every missing patch, not just on-demand ones");
assert.match(diff, /file\.loadMode === "too_large"/, "the commit viewer distinguishes too-large files from missing patches");
assert.match(server, /recordPublication\(cardId, "squash_merge", message, verdict\.sha\)/, "only a verified squash SHA enters publication history");
assert.match(server, /cardCheckout\(card\)/, "diff/preview/publication share the worker-first checkout resolver");
assert.doesNotMatch(server, /execFile\("git", \["commit"/, "publication never shells out to a local Git commit");
assert.match(server, /selectCardEnvironment\(environment, workerEnvironment/, "a card forwards the BB composer environment instead of replacing it with a preset");
assert.match(server, /continuingWorkerEnvironment\(row/, "later workers reuse the card's selected BB environment");
assert.match(server, /text: AUDIT_DONE_NUDGE, mentions: \[\], visibility: "agent-only"/, "automatic audit recovery stays out of the user conversation");
assert.match(server, /text: buildContinueNudge\(\), mentions: \[\], visibility: "agent-only"/, "automatic continuations stay out of the user conversation");

assert.match(app, /title="Git changes"/, "Done cards have a dedicated Git changes panel");
assert.match(app, /Commit workspace…/, "commit requires an explicit user action");
assert.match(app, /Save local commit to/, "a BB-selected default checkout is described as a local commit");
assert.match(app, /default checkout selected in BB/, "the publication panel explains that BB's checkout choice is respected");
assert.match(app, /cannot fetch remote updates, merge incoming changes, push, or create a pull request/, "the publication panel does not promise remote synchronization the BB API does not expose");
assert.match(app, /Advanced Git operations/, "local squash integration is progressively disclosed");
assert.match(app, /DisclosureChevron open=\{advancedGitOpen\} \/>Advanced Git operations/, "the disclosure arrow reads explicit open state, never CSS hope");
assert.match(app, /publication\.pullRequest\.state === "draft" \? <Button/, "ready/draft resolves to one contextual action from PR state");
assert.match(app, /Squash branch locally/, "local squash integration uses plain-language copy");
assert.match(app, /Merge PR…/, "PR merge remains an explicit user action");
assert.match(publication, /submitting/, "publication confirmations prevent duplicate write requests");
assert.match(app, /Repository rules, approvals, checks, and merge queues remain authoritative/, "merge confirmation does not bypass repository policy");
assert.match(app, /Publication history/, "the user can audit prior publication actions");
assert.match(diff, /filesEpoch/, "commit files render as collapsed accordions with expand/collapse all");
assert.match(app, /Next: publish the branch\./, "a saved commit names its pending step as structure, not buried prose");
assert.doesNotMatch(app, /What remains to publish it/, "publish steps live as sections with action rows, never as buttons inside prose");
assert.doesNotMatch(app, /Push the branch — this panel runs/, "no call-to-action hides inside a paragraph anymore");
assert.match(app, /card && shouldShowBuildDiff\(\{ status: card\.status, stage: card\.stage, publicationDirty, recoveryKind:/, "the extracted Diff feature remains wired to card stage, dirty-tree state, and recovery state");
assert.match(app, /<BuildDiff[\s\S]*onOpenFile=\{setViewerFile\}/, "working-tree files continue to open in the shared artifact viewer");
assert.match(app, /Copy command/, "post-commit commands name what they copy instead of a bare Copy");
assert.match(app, /Saved locally on/, "a successful local save has an explicit outcome state");
assert.match(app, /View commit/, "recorded local commits can be inspected from Done");
assert.match(server, /parsePushRemoteUrl/, "the remote comes from git's own To line, never an assumed host");
assert.match(app, /branchWebLinks/, "branch links are built from the parsed remote, not hardcoded");
assert.match(publication, /publication && \(pushed \|\| publication\.pullRequest\) \? branchWebLinks/, "remote links need a branch proven to exist remotely, never a failed first push");
assert.match(app, /last push outcome unknown/, "an ended shell admits ignorance instead of claiming unpushed");
assert.match(app, /On GitHub/, "a pushed branch links out to the remote it landed on");
assert.match(app, /View branch ↗/, "the branch is one click away after pushing");
assert.match(app, /Open pull request ↗/, "the next step after pushing is a link, not a paragraph");
assert.match(app, /not pushed yet\./, "a saved commit states its remote truth instead of implying arrival");
assert.match(app, /pushed to origin\./, "a finished push reads as published in the outcome line");
assert.match(app, /Completed at \{verifiedHeadSha\.slice\(0, 7\)\}/, "completed cards anchor dirt to their verified HEAD");
assert.match(publication, /async function doAction\(\) \{[\s\S]*?\} finally \{[\s\S]*?await loadPublication\(\);[\s\S]*?await onChanged\(\);/, "the publication action finally block refreshes both publication and card state after partial failures");
assert.match(publication, /setPushTerminals\(\{ ok: false, error:/, "push-shell listing failures stay visible instead of disappearing");
assert.match(publication, /action === "sync" \? \[10000, 25000\] : \[8000, 20000\]/, "push and sync results refresh automatically at their established follow-up times");
assert.match(publication, /action === "push" \|\| action === "sync"[\s\S]*schedulePushRefresh\(action\)/, "both remote publication paths schedule delayed terminal refreshes");
assert.match(diff, /rpc\.call\("publicationCommitDiff", \{ cardId, commitSha: sha \}\)/, "commit review loads the selected SHA for the current card from the diff feature owner");
assert.match(publication, /function PublicationActions/, "publication write confirmations and execution have one focused owner");
assert.match(publication, /<CommitDiffReview[\s\S]*openCommit\(savedSha\)[\s\S]*openCommit\(event\.commitSha!\)/, "saved and historical commits both navigate through the diff feature owner");
assert.match(app, /<BuildPublication[\s\S]*onDirtyChange=\{setPublicationDirty\}/, "CardDetailBody delegates publication UI while observing dirty-tree state");
assert.doesNotMatch(readFileSync(join(root, "app.tsx"), "utf8"), /publicationPullRequestAction/, "CardDetailBody no longer owns publication RPC actions");

console.log("publication wiring test ok: BB owns writes, Done stays separate, actions are explicit and auditable");
