export declare function questionCopy(): {
  answerNeeded: string;
  answersNeeded: (count: number) => string;
  questionOf: (current: number, total: number) => string;
  questions: string;
  answered: string;
  other: string;
  customPlaceholder: string;
  skipped: string;
  skip: string;
  submitAnswer: string;
  submitAnswers: string;
  sending: string;
  back: string;
  next: string;
  continue: string;
  continueWithAnswers: (count: number) => string;
  batchProgress: (done: number, total: number, canSkip: boolean) => string;
  answersRemaining: (count: number, canSkip: boolean) => string;
  pickOneOrMore: string;
  recoveryHeading: string;
};
export declare function englishQuestionContentError(question: unknown, options?: Array<{ label?: unknown; description?: unknown }> | null): string | null;
